### PR TITLE
bulk eftch for timezones

### PR DESCRIPTION
**Pull request by mantikafasi**
# Positives
* AAGaming doesnt bother me with it again
* makes less http requests
* AAGamings ISP wont have to look at his traffic again

# Negatives
* it fetches users every 5 seconds meaning if user entered someones profile before it fetched they wont able see their timezone

### CODE REVIEW

**Comment by AAGaming00** [comment]
explode

**Comment by nyakowint** [comment]
I trust that you didn't break anything lol :shipit:

**Comment by mantikafasi** [comment]
what can happen at worst :trollface:

**Comment by AAGaming00** [comment]
little did manti know he would explod in 3 minutes

**Pull request merged**
